import type { SpeakingPart } from "@/types";

export const speakingQuestions: Record<SpeakingPart, string[]> = {
  "Part 1": [
    "Do you work or study?",
    "What subject do you enjoy most?",
    "How do you usually spend your weekends?",
    "Do you prefer studying alone or with other people?",
    "What kind of music do you like?",
    "How often do you use public transport?",
    "Do you like the city you live in?",
    "What food do you often eat at home?",
    "Do you enjoy reading books?",
    "What kind of weather do you like?",
    "Do you often take photos?",
    "How do you keep in touch with friends?",
    "Do you like shopping online?",
    "What sport would you like to try?",
    "Do you prefer mornings or evenings?",
    "What was your favorite subject at school?",
    "Do you like watching films?",
    "How do you relax after a busy day?",
    "Do you often make plans?",
    "What app do you use most often?",
  ],
  "Part 2": [
    "Describe a person who encouraged you to achieve a goal.",
    "Describe a useful website you often visit.",
    "Describe a place in your city where you like to study.",
    "Describe a time when you solved a difficult problem.",
    "Describe a book that changed your way of thinking.",
    "Describe a memorable trip you took with someone.",
    "Describe a skill you would like to learn in the future.",
    "Describe an item you bought that was useful.",
    "Describe a speech or presentation you remember.",
    "Describe a traditional festival in your country.",
    "Describe a time when you received helpful advice.",
    "Describe a quiet place where you can relax.",
    "Describe a project you completed successfully.",
    "Describe a person who is good at their job.",
    "Describe a time when you had to wait for something.",
    "Describe an important decision you made.",
    "Describe a city you would like to visit again.",
    "Describe a piece of technology you use every day.",
    "Describe a time when you learned from a mistake.",
    "Describe an activity that helps you stay healthy.",
  ],
  "Part 3": [
    "Why do some people prefer practical skills to academic knowledge?",
    "How can schools help students become more confident speakers?",
    "Do you think technology has changed the way people learn languages?",
    "What makes a city a good place for young people to live?",
    "Should companies provide more training for their employees?",
    "How important is it for people to understand other cultures?",
    "Why do some people find it hard to manage their time?",
    "Do you think people read fewer books than in the past?",
    "What can governments do to protect the environment?",
    "How has online shopping changed local businesses?",
    "Why is teamwork important in education and work?",
    "Should children learn how to make financial decisions at school?",
    "How can people keep a healthy balance between work and life?",
    "What qualities make someone a good leader?",
    "Do you think travel is necessary for understanding the world?",
    "How does advertising influence young people?",
    "Why are public spaces important in modern cities?",
    "Should people change jobs frequently to gain experience?",
    "How can families support students during exam preparation?",
    "What role should art and music play in education?",
  ],
};

export function getRandomQuestion(part: SpeakingPart) {
  const questions = speakingQuestions[part];
  return questions[Math.floor(Math.random() * questions.length)];
}
